name: Build crDroid Nethunter Kernel OP8T (V4)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cài đặt môi trường (Dependencies)
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 python3
        
        # Ép hệ thống dùng Python 2 làm mặc định
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Tải Trình biên dịch (Proton Clang)
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

    - name: Tải Source Kernel crDroid Nethunter
      run: |
        git clone --depth=1 https://github.com/flypatriot/crdroid_12_kernel.git -b 12.1-nethunter kernel-source

    - name: Tiến hành Build Kernel
      run: |
        cd kernel-source
        export PATH="$GITHUB_WORKSPACE/clang/bin:$PATH"

        MAKE_ARGS="O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1"

        make $MAKE_ARGS clean
        make $MAKE_ARGS mrproper
        make $MAKE_ARGS nethunter_defconfig
        make -j$(nproc --all) $MAKE_ARGS Image

    - name: Đóng gói siêu mượt với AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git
        cd AnyKernel3
        
        # Xóa rác
        rm -rf patch/ modules/ ramdisk/
        
        # V4: BẬT CHẾ ĐỘ AUTO - THẢ RÔNG CHO TOOL TỰ DÒ TÌM PHÂN VÙNG
        sed -i 's/kernel.string=.*/kernel.string=crDroid Nethunter OP8T V4/g' anykernel.sh
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' anykernel.sh
        
        # Cho tool tự nhận diện phân vùng A/B
        sed -i 's/is_slot_device=0/is_slot_device=auto/g' anykernel.sh
        
        # Xóa mẹ đường dẫn cũ, nạp đường dẫn auto
        sed -i 's|block=.*|block=auto;|g' anykernel.sh

        cp ../kernel-source/out/arch/arm64/boot/Image ./
        zip -r9 ../Nethunter-Kernel-crDroid-OP8T-V4.zip * -x .git README.md *placeholder

    - name: Upload File ZIP lên Github
      uses: actions/upload-artifact@v4
      with:
        name: Nethunter-Kernel-crDroid-OP8T-V4
        path: Nethunter-Kernel-crDroid-OP8T-V4.zip
